# 0.1.1. Load from a txt file


In [6]:
#0.1.1
#import the numpy libaray as np
import numpy as np
#Define the file path for the data file
file_path="salaries.txt"
#load the file from the specified file using numpy's loadtxt function
data_array=np.loadtxt(file_path,delimiter=',')
#print the loaded data array
print(data_array)

[[  1.   2.   3.   4.   5.]
 [432. 411. 438. 442. 465.]
 [466. 475. 412. 428. 423.]
 [429. 407. 469. 477. 434.]
 [483. 474. 468. 485. 425.]
 [437. 470. 478. 495. 450.]
 [417. 471. 467. 477. 437.]
 [402. 414. 473. 436. 483.]
 [457. 433. 485. 415. 461.]
 [410. 471. 483. 474. 433.]
 [420. 403. 438. 485. 433.]
 [470. 487. 407. 408. 401.]
 [486. 432. 451. 405. 456.]
 [438. 484. 413. 445. 411.]
 [461. 475. 493. 474. 400.]
 [451. 416. 415. 412. 475.]
 [478. 499. 421. 401. 421.]
 [452. 481. 498. 450. 413.]
 [406. 426. 497. 403. 462.]
 [498. 412. 416. 431. 461.]
 [451. 445. 492. 472. 446.]
 [449. 491. 458. 461. 460.]
 [480. 420. 473. 445. 468.]
 [455. 425. 466. 463. 473.]
 [449. 414. 405. 460. 402.]
 [422. 441. 453. 461. 429.]
 [496. 443. 461. 470. 434.]
 [433. 466. 432. 492. 461.]
 [414. 485. 491. 467. 410.]
 [485. 470. 442. 483. 422.]
 [482. 419. 493. 418. 417.]]


# 0.1.2. Load from CSV file


In [7]:
# Import the NumPy library as np
import numpy as np

# Define the file path for the data file
file_path = "salaries.csv"

# Load the data from the specified file using NumPy's loadtxt function, assuming the data is comma-separated
data_array = np.loadtxt(file_path, delimiter=',')

# Print the loaded data array
print(data_array)

[[  1.   2.   3.   4.   5.]
 [432. 411. 438. 442. 465.]
 [466. 475. 412. 428. 423.]
 [429. 407. 469. 477. 434.]
 [483. 474. 468. 485. 425.]
 [437. 470. 478. 495. 450.]
 [417. 471. 467. 477. 437.]
 [402. 414. 473. 436. 483.]
 [457. 433. 485. 415. 461.]
 [410. 471. 483. 474. 433.]
 [420. 403. 438. 485. 433.]
 [470. 487. 407. 408. 401.]
 [486. 432. 451. 405. 456.]
 [438. 484. 413. 445. 411.]
 [461. 475. 493. 474. 400.]
 [451. 416. 415. 412. 475.]
 [478. 499. 421. 401. 421.]
 [452. 481. 498. 450. 413.]
 [406. 426. 497. 403. 462.]
 [498. 412. 416. 431. 461.]
 [451. 445. 492. 472. 446.]
 [449. 491. 458. 461. 460.]
 [480. 420. 473. 445. 468.]
 [455. 425. 466. 463. 473.]
 [449. 414. 405. 460. 402.]
 [422. 441. 453. 461. 429.]
 [496. 443. 461. 470. 434.]
 [433. 466. 432. 492. 461.]
 [414. 485. 491. 467. 410.]
 [485. 470. 442. 483. 422.]
 [482. 419. 493. 418. 417.]]


# 0.1.3. Make a list into an array


In [1]:
import numpy as np

def list_to_array(input_list, dtype=float, order='C'):
    """
    Convert a list to a NumPy array with specified data type and order.

    Parameters:
    - input_list: list
        The input list to be converted to a NumPy array.
    - dtype: data-type, optional
        Desired data-type for the array (default is float).
    - order: {'C', 'F'}, optional
        Specify the order of the array ('C' for row-major, 'F' for column-major).

    Returns:
    - numpy.ndarray
        NumPy array constructed from the input list.
    """
    return np.array(input_list, dtype=dtype, order=order)

my_list = [1, 2, 3, 4,5,6]
result_array = list_to_array(my_list, dtype=int, order='C')
print(result_array)

[1 2 3 4 5 6]


# 0.2.4. Matrix Operations



In [2]:
#0.2.4
# Import NumPy library
import numpy as np  


# Check if the matrix is equal to its transpose
def is_symmetric(matrix):
    return np.allclose(matrix, matrix.T)

# Check if the matrix is equal to the negative of its transpose
def is_anti_symmetric(matrix):
    return np.allclose(matrix, -matrix.T)

# Check if the matrix squared is equal to the matrix itself
def is_idempotent(matrix):
    return np.allclose(np.dot(matrix, matrix), matrix)

# Check if the matrix is equal to its conjugate transpose
def is_hermitian(matrix):
    return np.allclose(matrix, np.conj(matrix).T)

# Check if the product of the matrix and its conjugate transpose is equal to the identity matrix
def is_unitary(matrix):
    product = np.dot(matrix, np.conj(matrix).T)
    return np.allclose(product, np.eye(matrix.shape[0]))

matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])  # Replace with your matrix

# Print whether the matrix has each specified property as in ture and false
print(f"Symmetric: {is_symmetric(matrix)}")
print(f"Anti-symmetric: {is_anti_symmetric(matrix)}")
print(f"Idempotent: {is_idempotent(matrix)}")
print(f"Hermitian: {is_hermitian(matrix)}")
print(f"Unitary: {is_unitary(matrix)}")

Symmetric: True
Anti-symmetric: False
Idempotent: False
Hermitian: True
Unitary: False


# 0.2.1. Making Block diagonal arrays


In [3]:
#0.2.1
import numpy as np

# Generate three random 3x3 matrices
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
matrix3 = np.random.rand(3, 3)

# Create a block diagonal matrix
block_diagonal_matrix = np.block([[matrix1, np.zeros((3, 3)), np.zeros((3, 3))],
                                  [np.zeros((3, 3)), matrix2, np.zeros((3, 3))],
                                  [np.zeros((3, 3)), np.zeros((3, 3)), matrix3]])
#print the block_diagonal_matrix
print(block_diagonal_matrix)

[[0.59694939 0.25212988 0.82988348 0.         0.         0.
  0.         0.         0.        ]
 [0.62206692 0.68963409 0.60909832 0.         0.         0.
  0.         0.         0.        ]
 [0.90325982 0.18232347 0.63353475 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.20436912 0.40014679 0.30533279
  0.         0.         0.        ]
 [0.         0.         0.         0.75059074 0.94907197 0.13985356
  0.         0.         0.        ]
 [0.         0.         0.         0.72126472 0.37092685 0.67828689
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.0777307  0.34379008 0.49346809]
 [0.         0.         0.         0.         0.         0.
  0.07937365 0.7727087  0.05640044]
 [0.         0.         0.         0.         0.         0.
  0.84896102 0.63201084 0.124752  ]]


# 0.2.2. Off diagonal block matrix


In [2]:
#0.2.2

import numpy as np

#defined a function named random_matrix it  takes a parameter size
def random_matrix(size):
    return np.random.rand(size, size)

# Number of blocks and size of each block
num_blocks = 3
block_size = 4

# Create random matrices for off-diagonal blocks
off_diag_blocks = [random_matrix(block_size) for _ in range(num_blocks)]

# Construct the off-diagonal block matrix
block_matrix = np.block([[np.zeros((block_size, block_size))] * num_blocks, off_diag_blocks])

print(block_matrix)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.73139739 0.98366587 0.0032844  0.11303725 0.61784373 0.26465025
  0.84974584 0.77958518 0.68079088 0.47893016 0.83165165 0.91825417]
 [0.51015498 0.91616014 0.58979797 0.70822871 0.72707814 0.30107723
  0.45136209 0.97177674 0.90378337 0.84356888 0.32639253 0.34456806]
 [0.50844261 0.69671781 0.90561777 0.58371951 0.43478791 0.59630302
  0.42736959 0.83099008 0.88805275 0.63485024 0.62069568 0.36645001]
 [0.08973756 0.33910256 0.02612046 0.95584448 0.11854589 0.19339513
  0.8

# 0.2.5. Array Operations


In [3]:
#0.2.5
import numpy as np

# Assuming arr is your 1D array with length as a multiple of 3
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the 1D array into a 2D array with 3 rows
arr_2d = arr.reshape(-1, 3)

print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 0.2.6. Avoiding element-wise comparison


In [4]:
#0.2.6
import numpy as np

# Assuming arr is your 1D array with length as a multiple of 3
arr = np.array([1, 2, 3, 1, 5, 6, 1, 8, 9, 1, 11, 12])

# Extract elements at positions 3n
selected_elements = arr[::3]

# Check if all elements are the same
are_all_elements_same = np.all(selected_elements == selected_elements[0])
#print the result
print(are_all_elements_same)

True


# 0.3.2. Euler’s formula


In [5]:
#0.3.2.
import numpy as np

# Step 1: Create a matrix representing theta (in radians)
theta = np.pi / 4  # Example angle of pi/4 radians
matrix = np.array([[theta]])

# Step 2: Multiply the matrix by the imaginary unit i
matrix_iota = 1j * matrix

# Step 3: Take the matrix exponential
result = np.exp(matrix_iota)

print(result)

[[0.70710678+0.70710678j]]


# 0.4.1. Array creation


In [4]:
#0.4.1
import numpy as np
#Defined a function named load_salaries_csv it takes a parameter "file_path"
def load_salaries_csv(file_path): 
   # Load data from a CSV file into a NumPy array.
    #NumPy array containing the data from the CSV file.
    data_array = np.genfromtxt(file_path, delimiter=',', skip_header=1)
    #it will return the data_array
    return data_array
#Define the file path for the data file
file_path = 'salaries.csv'
#call the function here
salaries_data = load_salaries_csv(file_path)
#it will print the data in aaray
print(salaries_data)

[[432. 411. 438. 442. 465.]
 [466. 475. 412. 428. 423.]
 [429. 407. 469. 477. 434.]
 [483. 474. 468. 485. 425.]
 [437. 470. 478. 495. 450.]
 [417. 471. 467. 477. 437.]
 [402. 414. 473. 436. 483.]
 [457. 433. 485. 415. 461.]
 [410. 471. 483. 474. 433.]
 [420. 403. 438. 485. 433.]
 [470. 487. 407. 408. 401.]
 [486. 432. 451. 405. 456.]
 [438. 484. 413. 445. 411.]
 [461. 475. 493. 474. 400.]
 [451. 416. 415. 412. 475.]
 [478. 499. 421. 401. 421.]
 [452. 481. 498. 450. 413.]
 [406. 426. 497. 403. 462.]
 [498. 412. 416. 431. 461.]
 [451. 445. 492. 472. 446.]
 [449. 491. 458. 461. 460.]
 [480. 420. 473. 445. 468.]
 [455. 425. 466. 463. 473.]
 [449. 414. 405. 460. 402.]
 [422. 441. 453. 461. 429.]
 [496. 443. 461. 470. 434.]
 [433. 466. 432. 492. 461.]
 [414. 485. 491. 467. 410.]
 [485. 470. 442. 483. 422.]
 [482. 419. 493. 418. 417.]]


# 0.4.4. Adding new rows


In [11]:
#0.4.4

import numpy as np
#Define a function named add_row it takes two paratmers "matrix" amd new_row
def add_row(matrix, new_row):
    
   
   # Updated matrix with the new row added
    
    return np.vstack([matrix, new_row])

# Assuming 'existing_matrix' is your existing (i, n) shaped matrix
# and 'new_row_data' is the data for the new row to be added
existing_matrix = np.array([[1, 2, 3], [4, 5, 6]])
new_row_data = np.array([7, 8, 9])

# Adding a new row to the matrix
updated_matrix = add_row(existing_matrix, new_row_data)

# Print the updated matrix
print("Updated Matrix:")
print(updated_matrix)

Updated Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 0.4.6. Statistics


In [8]:
#0.4.6
import numpy as np

# Load the data from the csv file
data = np.genfromtxt('salaries.csv', delimiter=',', skip_header=1)

# Calculate total income of the people
total_income = np.sum(data[:, 0])

# Calculate mean and standard deviation of the income of each person
mean_income_per_person = np.mean(data[:, 0])
std_dev_income_per_person = np.std(data[:, 0])

# Calculate mean and standard deviation day wise
mean_income_day_wise = np.mean(np.sum(data[:, 0].reshape(-1, 1) * data[:, 1:], axis=0))
std_dev_income_day_wise = np.std(np.sum(data[:, 0].reshape(-1, 1) * data[:, 1:], axis=0))

# Print the results..............
print("Total Income of the people:", total_income)
print("Mean Income per person:", mean_income_per_person)
print("Standard Deviation of Income per person:", std_dev_income_per_person)
print("Mean Income day wise:", mean_income_day_wise)
print("Standard Deviation of Income day wise:", std_dev_income_day_wise)

Total Income of the people: 13509.0
Mean Income per person: 450.3
Standard Deviation of Income per person: 27.61056561052912
Mean Income day wise: 6058767.25
Standard Deviation of Income day wise: 84250.09082895698


# 0.4.5. Adding new people


In [10]:
#0.4.5
import numpy as np

# Load the data from the CSV file
data = np.genfromtxt('salaries.csv', delimiter=',', skip_header=1)

# Assuming 'new_person_wage' is the wage of the new person before joining
new_person_wage = 0

# Create an array for the new person with initial wage recorded as 0
new_person_data = np.full((data.shape[0], 1), new_person_wage)

# Concatenate the new person data to the existing data array
data = np.concatenate((data, new_person_data), axis=1)

# Print the updated data
print("Updated Data:")
print(data)

Updated Data:
[[432. 411. 438. 442. 465.   0.]
 [466. 475. 412. 428. 423.   0.]
 [429. 407. 469. 477. 434.   0.]
 [483. 474. 468. 485. 425.   0.]
 [437. 470. 478. 495. 450.   0.]
 [417. 471. 467. 477. 437.   0.]
 [402. 414. 473. 436. 483.   0.]
 [457. 433. 485. 415. 461.   0.]
 [410. 471. 483. 474. 433.   0.]
 [420. 403. 438. 485. 433.   0.]
 [470. 487. 407. 408. 401.   0.]
 [486. 432. 451. 405. 456.   0.]
 [438. 484. 413. 445. 411.   0.]
 [461. 475. 493. 474. 400.   0.]
 [451. 416. 415. 412. 475.   0.]
 [478. 499. 421. 401. 421.   0.]
 [452. 481. 498. 450. 413.   0.]
 [406. 426. 497. 403. 462.   0.]
 [498. 412. 416. 431. 461.   0.]
 [451. 445. 492. 472. 446.   0.]
 [449. 491. 458. 461. 460.   0.]
 [480. 420. 473. 445. 468.   0.]
 [455. 425. 466. 463. 473.   0.]
 [449. 414. 405. 460. 402.   0.]
 [422. 441. 453. 461. 429.   0.]
 [496. 443. 461. 470. 434.   0.]
 [433. 466. 432. 492. 461.   0.]
 [414. 485. 491. 467. 410.   0.]
 [485. 470. 442. 483. 422.   0.]
 [482. 419. 493. 418. 417.   

# 0.3.2. Euler’s formula


In [2]:


import numpy as np

# Define a sample matrix A
A = np.array([[1, 2], [3, 4]])

# Multiply the matrix by iota (imaginary unit)
A_iota = 1j * A

# Exponential of the resulting matrix
exp_A_iota = np.exp(A_iota)

# Calculate sin and cos of the original matrix
cos_A = np.cos(A)
sin_A = np.sin(A)

# Validate Euler's formula: e^(iA) = cos(A) + i * sin(A)
euler_validation = np.allclose(exp_A_iota, cos_A + 1j * sin_A)

# Print the all results
print("Matrix multiplied by i:\n", A_iota)
print("\nExponential of the matrix multiplied by i:\n", exp_A_iota)
print("\nCosine of the original matrix:\n", cos_A)
print("\nSine of the original matrix:\n", sin_A)
print("\nEuler's formula validation:", euler_validation)

Matrix multiplied by i:
 [[0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j]]

Exponential of the matrix multiplied by i:
 [[ 0.54030231+0.84147098j -0.41614684+0.90929743j]
 [-0.9899925 +0.14112001j -0.65364362-0.7568025j ]]

Cosine of the original matrix:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

Sine of the original matrix:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

Euler's formula validation: True
